version: '3.8'

services:
  sharebin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./uploads:/app/uploads  # Persist uploaded files
      - ./data:/app/data       # Persist database and settings
      - ./templates:/app/templates  # Serve templates
      - ./static:/app/static    # Serve static files
    environment:
      - SHAREBIN_PORT=80
